version: '3.4'


services: 
  go-builder-m:
    image: golang:1.14
    container_name: go-builder
    volumes: 
      - ./:/build:ro
  
  go-builder:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    container_name: dnsproxy-build

    
    