version: '3.4'


services: 
  quic-server:
    image: welikecode/dnsproxy
    container_name: "a.quic-server"
    command: "/app/dnsproxy -l 0.0.0.0  --tls-crt=/app/example.crt --tls-key=/app/example.key  --quic-port=784 -u 8.8.8.8:53 -u 1.1.1.1:53 -p 0 -v"
    expose:
     - 784
     - 53
    networks:
      quic_net:
        ipv4_address: 10.40.0.11
  
  quic-client:
    image: welikecode/dnsproxy
    container_name: "quic-client"
    extra_hosts:
    - "b.quic-server:10.40.0.11"
    command: "/app/dnsproxy -l 0.0.0.0 -p 53 -u quic://b.quic-server -u quic://a.quic-server  -v"
    ports:
      - '53:53/udp'
    networks:
      quic_net:
        ipv4_address: 10.40.0.2
    
networks:
  quic_net:
    ipam:
      config:
        - subnet: 10.40.0.0/24

    
    